export const TableHead = [
  "No",
  "본부",
  "현장명",
  "방이름",
  "활동구분",
  "생성일자",
  "번역속기록",
  "발표및 교육자료",
  "운영일자",
  "운영상태",
];

export const TableData = [
  {
    id: 1,
    headquarter: "대우건설",
    field: "3공구",
    roomName: "3공구 TBM 번역방",
    activity: "TBM",
    startDate: "2025-06-01",
    record: "다운로드",
    data: "다운로드",
    operationDate: "2025-06-05",
    status: ["운용", "참여중"],
  },
  {
    id: 2,
    headquarter: "본사",
    field: "교육센터",
    roomName: "안전교육 번역방",
    activity: "교육",
    startDate: "2025-06-02",
    record: "",
    data: "다운로드",
    operationDate: "2025-06-06",
    status: ["검증중", "검증중"],
  },
  {
    id: 3,
    headquarter: "서울본사",
    field: "대회의실",
    roomName: "월간 발표회",
    activity: "발표",
    startDate: "2025-06-03",
    record: "",
    data: "",
    operationDate: "2025-06-10",
    status: ["작성중", "준비중"],
  },
  {
    id: 4,
    headquarter: "대우건설",
    field: "4공구",
    roomName: "4공구 안전조회",
    activity: "안전조회",
    startDate: "2025-06-01",
    record: "다운로드",
    data: "",
    operationDate: "2025-06-05",
    status: ["운용", "시작하기"],
  },
  {
    id: 5,
    headquarter: "본사",
    field: "교육센터",
    roomName: "신입사원 교육",
    activity: "교육",
    startDate: "2025-06-02",
    record: "",
    data: "다운로드",
    operationDate: "2025-06-07",
    status: ["검증중", "검증중"],
  },
  {
    id: 6,
    headquarter: "대우건설",
    field: "5공구",
    roomName: "5공구 TBM 번역방",
    activity: "TBM",
    startDate: "2025-05-30",
    record: "다운로드",
    data: "다운로드",
    operationDate: "2025-06-04",
    status: ["운용", "참여중"],
  },
  {
    id: 7,
    headquarter: "서울본사",
    field: "임원회의실",
    roomName: "관리자 회의",
    activity: "발표",
    startDate: "2025-05-30",
    record: "",
    data: "",
    operationDate: "2025-06-08",
    status: ["작성중", "준비중"],
  },
];
