// export const TableHead = [
//   "No",
//   "본부",
//   "현장명",
//   "방이름",
//   "활동구분",
//   "생성일자",
//   "번역속기록",
//   "발표및 교육자료",
//   "운영일자",
//   "운영상태",
// ];

export const TableHead = [
  "table.no",
  "table.headquarter",
  "table.field",
  "table.roomName",
  "table.activity",
  "table.createdDate",
  "table.record",
  "table.presentation",
  "table.operationDate",
  "table.status",
];

export const TableData = [
  {
    id: 1,
    headquarter: "filter.headquarter.daewoo",
    field: "filter.field.zone3",
    roomName: "3공구 TBM 번역방",
    activity: "filter.activity.tbm",
    startDate: "2025-06-01",
    record: "common.download",
    data: "common.download",
    operationDate: "2025-06-05",
    status: ["status.operating", "status.joined"],
  },
  {
    id: 2,
    headquarter: "filter.headquarter.hq",
    field: "filter.field.training",
    roomName: "안전교육 번역방",
    activity: "filter.activity.edu",
    startDate: "2025-06-02",
    record: "",
    data: "common.download",
    operationDate: "2025-06-06",
    status: ["status.verifying", "status.verifying"],
  },
  {
    id: 3,
    headquarter: "filter.headquarter.seoul",
    field: "filter.field.conference",
    roomName: "월간 발표회",
    activity: "filter.activity.presentation",
    startDate: "2025-06-03",
    record: "",
    data: "",
    operationDate: "2025-06-10",
    status: ["status.writing", "status.ready"],
  },
  {
    id: 4,
    headquarter: "filter.headquarter.daewoo",
    field: "filter.field.zone4",
    roomName: "4공구 안전조회",
    activity: "filter.activity.check",
    startDate: "2025-06-01",
    record: "common.download",
    data: "",
    operationDate: "2025-06-05",
    status: ["status.operating", "status.start"],
  },
  {
    id: 5,
    headquarter: "filter.headquarter.hq",
    field: "filter.field.training",
    roomName: "신입사원 교육",
    activity: "filter.activity.edu",
    startDate: "2025-06-02",
    record: "",
    data: "common.download",
    operationDate: "2025-06-07",
    status: ["status.verifying", "status.verifying"],
  },
  {
    id: 6,
    headquarter: "filter.headquarter.daewoo",
    field: "filter.field.zone5",
    roomName: "5공구 TBM 번역방",
    activity: "filter.activity.tbm",
    startDate: "2025-05-30",
    record: "common.download",
    data: "common.download",
    operationDate: "2025-06-04",
    status: ["status.operating", "status.joined"],
  },
  {
    id: 7,
    headquarter: "filter.headquarter.seoul",
    field: "filter.field.executive",
    roomName: "관리자 회의",
    activity: "filter.activity.presentation",
    startDate: "2025-05-30",
    record: "",
    data: "",
    operationDate: "2025-06-08",
    status: ["status.writing", "status.ready"],
  },
];
